[package]
name = "keylogger-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "*"
reqwest = {version = "*", features = ["blocking"]}
base64-url = "1.4.10"